// SPDX-License-Identifier: Apache-2.0
package lab.network

import lab.cbor.Bytes
import ChainSync.DecodeResult
import KeepAlive.*
import scala.concurrent.duration.*

class KeepAliveSuite extends munit.FunSuite:
  private def b(hex: String): Bytes = Bytes.fromHex(hex).fold(fail(_), identity)
  private def right[A](value: Either[String, A]): A = value.fold(fail(_), identity)
  private def cookie(value: Int): Cookie = right(Cookie.from(value))
  private def failed[A](result: DecodeResult[A]): Unit = result match
    case DecodeResult.Failed(_) => ()
    case other                  => fail(s"expected Failed, got $other")

  // Literal fixtures transcribed from the pinned codec, not generated by this encoder.
  private val literals: Vector[(String, State, Role, Message, State)] = Vector(
    ("820000", State.Client, Role.Client, Message.Request(cookie(0)), State.Server),
    ("820017", State.Client, Role.Client, Message.Request(cookie(23)), State.Server),
    ("82001818", State.Client, Role.Client, Message.Request(cookie(24)), State.Server),
    ("820018ff", State.Client, Role.Client, Message.Request(cookie(255)), State.Server),
    ("8200190100", State.Client, Role.Client, Message.Request(cookie(256)), State.Server),
    ("820019ffff", State.Client, Role.Client, Message.Request(cookie(65535)), State.Server),
    ("820100", State.Server, Role.Server, Message.Response(cookie(0)), State.Client),
    ("820119ffff", State.Server, Role.Server, Message.Response(cookie(65535)), State.Client),
    ("8102", State.Client, Role.Client, Message.Done, State.Done)
  )

  literals.foreach { case (hex, state, role, message, next) =>
    test(s"literal $hex: exact encode/decode, every truncation, consumed prefix and suffix") {
      val wire = b(hex)
      assertEquals(right(encode(state, role, message)), wire)
      assertEquals(right(decode(state, role, wire)), message)
      assertEquals(transition(state, role, message), Right(next))
      (0 until wire.size).foreach { cut =>
        val prefix = Bytes(wire.value.take(cut))
        assertEquals(decodePrefix(state, role, prefix), DecodeResult.NeedMore)
        assert(decode(state, role, prefix).isLeft)
      }
      val joined = Bytes(wire.value ++ b("8102").value)
      assertEquals(decodePrefix(state, role, joined), DecodeResult.Decoded(message, wire.size))
      assert(decode(state, role, joined).isLeft)
    }
  }

  test("all messages in all states from both senders; terminal and wrong agency fail") {
    for
      state <- State.values
      role <- Role.values
      (hex, expectedState, expectedRole, message, _) <- literals
    do
      val legal = state == expectedState && role == expectedRole
      assertEquals(transition(state, role, message).isRight, legal)
      assertEquals(encode(state, role, message).isRight, legal)
      if legal then assertEquals(right(decode(state, role, b(hex))), message)
      else failed(decodePrefix(state, role, b(hex)))
    failed(decodePrefix(State.Done, Role.Client, Bytes(Vector.empty)))
    failed(decodePrefix(State.Done, Role.Server, Bytes(Vector.empty)))
    failed(decodePrefix(State.Client, Role.Server, Bytes(Vector.empty)))
    failed(decodePrefix(State.Server, Role.Client, Bytes(Vector.empty)))
  }

  test("UInt16 is checked at construction and before narrowing decoded values") {
    Vector(Int.MinValue, -1, 65536, Int.MaxValue).foreach(n => assert(Cookie.from(n).isLeft))
    Vector(0, 23, 24, 255, 256, 65535).foreach(n => assertEquals(cookie(n).value, n))
    assertEquals(cookie(65535), cookie(65535))
    assertEquals(cookie(65535).hashCode, cookie(65535).hashCode)
    Vector(
      "820020",
      "820039ffff",
      "82001a00010000",
      "82001b0000000100000000",
      "82001bffffffffffffffff"
    ).foreach(hex => failed(decodePrefix(State.Client, Role.Client, b(hex))))
  }

  test("definite non-shortest numeric and list-length forms remain accepted") {
    val fixtures = Vector(
      "980218001800" -> Message.Request(cookie(0)),
      "990002190000190018" -> Message.Request(cookie(24)),
      "82001a0000ffff" -> Message.Request(cookie(65535)),
      "82001b000000000000ffff" -> Message.Request(cookie(65535)),
      "810218" -> Message.Done // Prefix decoder must leave the unrelated suffix untouched.
    )
    fixtures.dropRight(1).foreach { case (hex, msg) =>
      assertEquals(right(decode(State.Client, Role.Client, b(hex))), msg)
      (0 until b(hex).size).foreach { cut =>
        assertEquals(
          decodePrefix(State.Client, Role.Client, Bytes(b(hex).value.take(cut))),
          DecodeResult.NeedMore
        )
      }
    }
    assertEquals(
      decodePrefix(State.Client, Role.Client, b("810218")),
      DecodeResult.Decoded(Message.Done, 2)
    )
    assertEquals(right(decode(State.Client, Role.Client, b("98011802"))), Message.Done)
    assertEquals(
      right(decode(State.Server, Role.Server, b("82011800"))),
      Message.Response(cookie(0))
    )
  }

  test("reject indefinite arrays, wrong arity/type, unknown or oversized tags, bad cookies") {
    Vector(
      "9f0000ff",
      "80",
      "83000000",
      "8100",
      "8202",
      "8120",
      "8103",
      "811b0000000100000002",
      "82001f",
      "8200ff",
      "820040",
      "820080",
      "8200f6",
      "a20000",
      "82031b0000000000000000",
      "820100",
      "8101",
      "81ff"
    )
      .foreach(hex => failed(decodePrefix(State.Client, Role.Client, b(hex))))
    Vector("8102", "820000", "83010000", "820120", "82011a00010000")
      .foreach(hex => failed(decodePrefix(State.Server, Role.Server, b(hex))))
  }

  test("message bounds apply to consumed prefix; invalid and structural bounds fail closed") {
    val msg = Message.Request(cookie(65535))
    val wire = b("820019ffff")
    assertEquals(right(encode(State.Client, Role.Client, msg, Limits(maxMessageBytes = 5))), wire)
    assert(encode(State.Client, Role.Client, msg, Limits(maxMessageBytes = 4)).isLeft)
    failed(decodePrefix(State.Client, Role.Client, wire, Limits(maxMessageBytes = 4)))
    // Declared uint width exceeds limit before waiting for its body.
    failed(decodePrefix(State.Client, Role.Client, b("82001b"), Limits(maxMessageBytes = 5)))
    val coalesced = Bytes(wire.value ++ wire.value)
    assertEquals(
      decodePrefix(State.Client, Role.Client, coalesced, Limits(maxMessageBytes = 5)),
      DecodeResult.Decoded(msg, 5)
    )
    Vector(
      Limits(maxMessageBytes = 0),
      Limits(maxMessageBytes = 65536),
      Limits(maxDepth = -1),
      Limits(maxDepth = 65),
      Limits(maxItems = 0),
      Limits(maxItems = 65536),
      Limits(maxDepth = 0),
      Limits(maxItems = 2)
    ).foreach { limits =>
      assert(encode(State.Client, Role.Client, msg, limits).isLeft)
      failed(decodePrefix(State.Client, Role.Client, wire, limits))
    }
  }

  test("cookie matching is mandatory and independent from valid wire decoding") {
    val response = right(decode(State.Server, Role.Server, b("820100")))
    assertEquals(matchResponse(Some(cookie(0)), response), Right(()))
    assert(matchResponse(Some(cookie(1)), response).isLeft)
    assert(matchResponse(None, response).isLeft)
    assert(matchResponse(Some(cookie(0)), Message.Request(cookie(0))).isLeft)
    assert(matchResponse(Some(cookie(0)), Message.Done).isLeft)
    // After matching and clearing the outstanding cookie, the same response is a duplicate.
    val outstanding = Some(cookie(0))
    assert(matchResponse(outstanding, response).isRight)
    assert(matchResponse(None, response).isLeft)
    assert(transition(State.Server, Role.Client, Message.Request(cookie(1))).isLeft)
    assert(transition(State.Server, Role.Client, Message.Done).isLeft)
  }

  test("coalesced request/response/done advances only by exact consumed prefixes") {
    var pending = b("8200008201008102")
    var state = State.Client
    Vector(Role.Client, Role.Server, Role.Client).foreach { role =>
      decodePrefix(state, role, pending) match
        case DecodeResult.Decoded(message, consumed) =>
          state = right(transition(state, role, message))
          pending = Bytes(pending.value.drop(consumed))
        case other => fail(s"unexpected $other")
    }
    assertEquals(state, State.Done)
    assertEquals(pending.size, 0)
  }

  test("source metadata remains distinct from any runtime scheduling or ingress policy") {
    assertEquals(MiniProtocolId, 8)
    assertEquals(CodecVersion, 2)
    assertEquals(Limits().maxMessageBytes, 65535)
    assertEquals(UpstreamTimeLimits.client, 97.seconds)
    assertEquals(UpstreamTimeLimits.server, 60.seconds)
    assertEquals(direction(Role.Client), Mux.Direction.Initiator)
    assertEquals(direction(Role.Server), Mux.Direction.Responder)
  }
