// SPDX-License-Identifier: Apache-2.0
package lab.network

import lab.cbor.Bytes
import ChainSync.{DecodeResult, Role}
import TxSubmission2.{State, Message}

class TxSubmission2Suite extends munit.FunSuite:
  private def hex(s: String) = Bytes.fromHex(s).toOption.get
  private val id = hex("d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6c")
  private val tx = hex("84a0a0f5f6")
  private val offer = RelayOffer(id, 10)
  // Source-derived literal fixtures, deliberately not generated by the implementation.
  private val vectors = Vector(
    (State.Init, Role.Client, Message.Init, "8106"),
    (State.Idle, Role.Server, Message.RequestIds(true, 0, 10), "8400f5000a"),
    (State.Idle, Role.Server, Message.RequestIds(false, 1, 0), "8400f40100"),
    (
      State.Ids(true),
      Role.Client,
      Message.ReplyIds(Vector(offer)),
      "82019f8282065820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6c0aff"
    ),
    (State.Ids(false), Role.Client, Message.ReplyIds(Vector.empty), "82019fff"),
    (
      State.Idle,
      Role.Server,
      Message.RequestTxs(Vector(id)),
      "82029f82065820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6cff"
    ),
    (State.Txs, Role.Client, Message.ReplyTxs(Vector(tx)), "82039f8206d8184584a0a0f5f6ff"),
    (State.Ids(true), Role.Client, Message.Done, "8104")
  )
  test("pinned source-derived golden vectors encode and decode exactly") {
    vectors.foreach { case (state, role, message, wire) =>
      assertEquals(TxSubmission2.encode(state, role, message), Right(hex(wire)))
      assertEquals(TxSubmission2.decode(state, role, hex(wire)), Right(message))
    }
  }
  test("every truncated golden prefix needs more; suffix remains distinct") {
    vectors.foreach { case (state, role, message, wire) =>
      val bytes = hex(wire)
      (0 until bytes.size).foreach(n =>
        assertEquals(
          TxSubmission2.decodePrefix(state, role, Bytes(bytes.value.take(n))),
          DecodeResult.NeedMore
        )
      )
      assertEquals(
        TxSubmission2.decodePrefix(state, role, Bytes(bytes.value ++ Vector(0.toByte))),
        DecodeResult.Decoded(message, bytes.size)
      )
      assert(TxSubmission2.decode(state, role, Bytes(bytes.value ++ Vector(0.toByte))).isLeft)
    }
  }
  test("wrong agency, definite inner lists, era, arity, tag and blocking empty reply rejected") {
    vectors.foreach { case (state, role, message, _) =>
      val wrong = if role == Role.Client then Role.Server else Role.Client
      assert(TxSubmission2.encode(state, wrong, message).isLeft)
    }
    Vector(
      "820280",
      "82029f82055820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6cff",
      "8102",
      "82029f5820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6cff",
      "82029f8206581f" + "00" * 31 + "ff"
    ).foreach(w => assert(TxSubmission2.decode(State.Idle, Role.Server, hex(w)).isLeft))
    assert(TxSubmission2.decode(State.Ids(true), Role.Client, hex("82019fff")).isLeft)
    assert(TxSubmission2.decode(State.Ids(false), Role.Client, hex("8104")).isLeft)
  }
  test("uint16 bounds before narrowing and noncanonical numeric forms") {
    assert(TxSubmission2.decode(State.Idle, Role.Server, hex("8400f51a0001000001")).isLeft)
    assertEquals(
      TxSubmission2.decode(State.Idle, Role.Server, hex("8400f518001801")),
      Right(Message.RequestIds(true, 0, 1))
    )
    assert(TxSubmission2.encode(State.Idle, Role.Server, Message.RequestIds(true, -1, 1)).isLeft)
    assert(
      TxSubmission2
        .decode(
          State.Ids(false),
          Role.Client,
          hex(
            "82019f8282065820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6c1b0000000100000000ff"
          )
        )
        .isLeft
    )
  }
  test("advertised GenTx size crosses byte-string header widths; original body identity retained") {
    Vector(23 -> 28L, 24 -> 30L, 255 -> 261L, 256 -> 263L, 65535 -> 65542L, 65536 -> 65545L)
      .foreach { case (n, expected) =>
        assertEquals(TxSubmission2.advertisedSize(n), Right(expected))
      }
    assert(TxSubmission2.advertisedSize(65537).isLeft)
    assertEquals(TxSubmission2.bodyId(tx), Right(id))
    assertEquals(TxSubmission2.bodyId(hex("84a0a10080f5f6")), Right(id))
    assert(TxSubmission2.bodyId(hex("84a0a0f5f600")).isLeft)
    assert(TxSubmission2.bodyId(hex("83a0a0f5")).isLeft)
  }
  test("blocking request window can exceed available lease; FIFO acknowledgement drains it") {
    val i = TxSubmission2.Inventory.create(Vector(offer)).toOption.get
    val (a, reply, ack) = i.requestIds(true, 0, 65535).toOption.get
    assertEquals(reply, Message.ReplyIds(Vector(offer)))
    assertEquals(ack, Vector.empty)
    val served = a.requestTxs(Vector(id)).toOption.get
    assert(served.requestTxs(Vector(id)).isLeft)
    val (_, done, acknowledged) = served.requestIds(true, 1, 10).toOption.get
    assertEquals(done, Message.Done)
    assertEquals(acknowledged, Vector(id))
  }
  test("unsolicited/repeated/duplicate/acknowledged body requests fail") {
    val start = TxSubmission2.Inventory.create(Vector(offer)).toOption.get
    assert(start.requestTxs(Vector(id)).isLeft)
    val advertised = start.requestIds(true, 0, 1).toOption.get._1
    assert(advertised.requestTxs(Vector(id, id)).isLeft)
    assert(advertised.requestTxs(Vector(hex("00" * 32))).isLeft)
    assert(advertised.requestIds(true, 0, 1).isLeft)
    assert(advertised.requestIds(false, 1, 1).isLeft)
    assert(advertised.requestIds(false, 2, 1).isLeft)
    assert(advertised.requestIds(false, 0, 0).isLeft)
    assert(start.requestIds(false, 0, 1).isLeft)
    assert(start.requestIds(true, 0, 0).isLeft)
    assert(advertised.requestIds(true, 1, 1).toOption.get._1.requestTxs(Vector(id)).isLeft)
  }
  test("partial acknowledgements remove oldest IDs and nonblocking replies may be empty") {
    val second = offer.copy(transactionId = hex("01" * 32))
    val initial = TxSubmission2.Inventory.create(Vector(offer, second)).toOption.get
    val advertised = initial.requestIds(true, 0, 2).toOption.get._1
    val (next, reply, ack) = advertised.requestIds(false, 1, 1).toOption.get
    assertEquals(ack, Vector(id))
    assertEquals(reply, Message.ReplyIds(Vector.empty))
    assert(next.requestTxs(Vector(id)).isLeft)
    assert(next.requestTxs(Vector(second.transactionId)).isRight)
  }
  test("inventory and wire collections have independent fixed eight-item bounds") {
    assert(TxSubmission2.Inventory.create(Vector.fill(2)(offer)).isLeft)
    assert(TxSubmission2.Inventory.create(Vector.fill(9)(offer)).isLeft)
    val wire =
      "82029f" + ("82065820d36a2619a672494604e11bb447cbcf5231e9f2ba25c2169177edc941bd50ad6c" * 9) + "ff"
    assert(TxSubmission2.decode(State.Idle, Role.Server, hex(wire)).isLeft)
    assert(
      TxSubmission2.encode(State.Txs, Role.Client, Message.ReplyTxs(Vector.fill(9)(tx))).isLeft
    )
  }

  test("large protocol messages segment into uint16 SDUs without widening legacy API") {
    val bytes = Bytes(Vector.fill(70000)(0.toByte))
    val frames =
      Mux.segmentProtocolMessage(bytes, 0L, Mux.Direction.Initiator, 65535, 4, 80000).toOption.get
    assertEquals(frames.map(_.payload.size), Vector(65535, 4465))
    assertEquals(Bytes(frames.flatMap(_.payload.value)), bytes)
    assert(Mux.segmentBounded(bytes, 0L, Mux.Direction.Initiator, 65535, 4, 80000).isLeft)
    assert(Mux.segmentProtocolMessage(bytes, 0L, Mux.Direction.Initiator, 65535, 4, 2500001).isLeft)
    assert(Mux.segmentProtocolMessage(bytes, 0L, Mux.Direction.Initiator, 65535, 4, 69999).isLeft)
  }

  test("indefinite transaction envelopes retain exact noncanonical and indefinite body identity") {
    Vector("a0", "a1001800", "bf001800ff").foreach { body =>
      val definite = hex("84" + body + "a0f5f6")
      val indefinite = hex("9f" + body + "a0f5f6ff")
      assertEquals(TxSubmission2.bodyId(indefinite), TxSubmission2.bodyId(definite))
      assertEquals(TxSubmission2.bodyId(indefinite), Right(lab.Blake2b.hash256.hash(hex(body))))
      val message = Message.ReplyTxs(Vector(indefinite))
      val encoded = TxSubmission2.encode(State.Txs, Role.Client, message).toOption.get
      assertEquals(TxSubmission2.decode(State.Txs, Role.Client, encoded), Right(message))
      assertEquals(
        TxSubmission2.advertisedSize(indefinite.size),
        TxSubmission2.advertisedSize(definite.size).map(_ + 1)
      )
    }
    assertNotEquals(
      TxSubmission2.bodyId(hex("9fa1001800a0f5f6ff")),
      TxSubmission2.bodyId(hex("9fa10000a0f5f6ff"))
    )
  }
  test(
    "indefinite envelope requires exactly four complete members and exactly one terminal break"
  ) {
    Vector(
      "9f",
      "9fff",
      "9fa0ff",
      "9fa0a0ff",
      "9fa0a0f5ff",
      "9fa0a0f5f6",
      "9fa0a0f5f600ff",
      "9fa0a0f5f6ffff",
      "9fa0a0f5f6ff00",
      "9fa0a0f5f6fe",
      "9fa0a0f5f6f8ff",
      "9f80a0f5f6ff",
      "9fa0a000f6ff",
      "9fbf00ffa0f5f6ff",
      "9fa0a0f5c0ff",
      "9fa0a0f5a100ff",
      "9fa0a0f59f00ff"
    ).foreach(raw => assert(TxSubmission2.bodyId(hex(raw)).isLeft, raw))
    val exact = hex("9fa0a10059fff6" + "00" * 65526 + "f5f6ff")
    assertEquals(exact.size, 65536)
    assertEquals(TxSubmission2.bodyId(exact), Right(id))
    assert(TxSubmission2.bodyId(Bytes(exact.value :+ 0.toByte)).isLeft)
    val deep = hex("9fa0a0f5" + "81" * 34 + "00ff")
    assert(TxSubmission2.bodyId(deep).isLeft)
  }
