cabal-version: 3.0
name: sustained-query-client
version: 0.0.0
build-type: Simple
license: Apache-2.0
library
  exposed-modules: Session, Transport, VerifySeed, StrictJson, Adapter, Projection
  default-language: Haskell2010
  build-depends:
    base >=4.18 && <4.19,
    bytestring, containers, text ==2.1.4, aeson ==2.2.5.0, attoparsec ==0.14.4, scientific ==0.3.8.1, crypton ==1.0.6, contra-tracer, io-classes ==1.8.0.1,
    network-mux ==0.11.0.0,
    cardano-protocol ==0.1.0.0, cardano-slotting ==0.2.2.0,
    cardano-diffusion:{cardano-diffusion,api,protocols} ==1.1.1.0,
    ouroboros-consensus:{ouroboros-consensus,cardano,protocol,diffusion} ==4.2.1.0,
    ouroboros-network:{api,framework,ouroboros-network,protocols} ==1.2.0.0,
    cardano-ledger-conway ==1.23.0.0,
    cardano-ledger-shelley ==1.19.0.1,
    cardano-ledger-core ==1.21.0.0,
    cardano-ledger-binary ==1.9.1.0

executable sustained-query-capture
  main-is: Main.hs
  hs-source-dirs: query
  default-language: Haskell2010
  ghc-options: -threaded -rtsopts -with-rtsopts=-N1
  build-depends:
    base >=4.18 && <4.19, sustained-query-client,
    cardano-ledger-byron ==1.3.0.0, cardano-protocol ==0.1.0.0,
    cardano-diffusion:api ==1.1.1.0,
    ouroboros-consensus:{ouroboros-consensus,cardano} ==4.2.1.0


executable sustained-query-offline
  main-is: Main.hs
  hs-source-dirs: offline
  default-language: Haskell2010
  ghc-options: -threaded -rtsopts -with-rtsopts=-N1
  build-depends:
    base >=4.18 && <4.19, sustained-query-client,
    bytestring, containers, aeson ==2.2.5.0, cborg, cardano-ledger-byron ==1.3.0.0,
    cardano-diffusion:api ==1.1.1.0, data-default ==0.8.0.2, strict-sop-core ==0.1.4.0, sop-extras ==0.4.2.0,
    cardano-protocol ==0.1.0.0, cardano-slotting ==0.2.2.0,
    cardano-ledger-conway ==1.23.0.0,
    cardano-ledger-shelley ==1.19.0.1,
    cardano-ledger-core ==1.21.0.0,
    cardano-ledger-binary ==1.9.1.0,
    ouroboros-consensus:{ouroboros-consensus,cardano,protocol} ==4.2.1.0,
    ouroboros-network:{api,protocols} ==1.2.0.0
